spring.application.name=easyOrder
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/easyorder
spring.datasource.username=root
spring.datasource.password=purplePower33*

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

